import {MigrationInterface, QueryRunner} from "typeorm";

export class tambahanKolom1657621062545 implements MigrationInterface {
    name = 'tambahanKolom1657621062545'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`namaPanggilan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`tempatLahir\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`bahasaSeharihari\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`saudaraKandung\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`saudaraTiri\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`saudaraAngkat\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`alamat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`kecamatan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`kelurahan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`kota\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`provinsi\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`kodepos\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`notelp\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`rtrw\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`pendidikanAyah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`pendidikanIbu\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`pekerjaanAyah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`pekerjaanIbu\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`namaWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`hubunganWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`pendidikanWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`pekerjaanWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`asalSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`namaSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`tglDanNmrIjzSTTB\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`namaSekolahAsal\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`dariTingkat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`diterimaTgl\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`noSuratKet\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`tahunTamat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`noIjzahSTTB\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`melanjutKeSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`kelasDitinggalkan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`keSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`keTingkat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`alasanKeluarSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` ADD \`tglKeluar\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`gender\` \`gender\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`agama\` \`agama\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`birthDate\` \`birthDate\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherName\` \`motherName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherNumber\` \`motherNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherName\` \`fatherName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherNumber\` \`fatherNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`joinDate\` \`joinDate\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`status\` \`status\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`bloodType\` \`bloodType\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`uangKegiatan\` \`uangKegiatan\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keterangan\` \`keterangan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakBaru\` \`anakBaru\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`totalTunggakan\` \`totalTunggakan\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kewarganegaraan\` \`kewarganegaraan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakKe\` \`anakKe\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`language\` \`language\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tinggalPada\` \`tinggalPada\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`jarakKeSekolah\` \`jarakKeSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_b2731e10aef7f886a08c552290e\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tanggalBayar\` \`tanggalBayar\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`studentId\` \`studentId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_b2731e10aef7f886a08c552290e\` FOREIGN KEY (\`studentId\`) REFERENCES \`students\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_b2731e10aef7f886a08c552290e\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`studentId\` \`studentId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tanggalBayar\` \`tanggalBayar\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_b2731e10aef7f886a08c552290e\` FOREIGN KEY (\`studentId\`) REFERENCES \`students\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`jarakKeSekolah\` \`jarakKeSekolah\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tinggalPada\` \`tinggalPada\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`language\` \`language\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakKe\` \`anakKe\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kewarganegaraan\` \`kewarganegaraan\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`totalTunggakan\` \`totalTunggakan\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakBaru\` \`anakBaru\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keterangan\` \`keterangan\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`uangKegiatan\` \`uangKegiatan\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`bloodType\` \`bloodType\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`status\` \`status\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`joinDate\` \`joinDate\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherNumber\` \`fatherNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherName\` \`fatherName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherNumber\` \`motherNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherName\` \`motherName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`birthDate\` \`birthDate\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`agama\` \`agama\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`gender\` \`gender\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`tglKeluar\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`alasanKeluarSekolah\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`keTingkat\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`keSekolah\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`kelasDitinggalkan\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`melanjutKeSekolah\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`noIjzahSTTB\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`tahunTamat\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`noSuratKet\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`diterimaTgl\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`dariTingkat\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`namaSekolahAsal\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`tglDanNmrIjzSTTB\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`namaSekolah\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`asalSekolah\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`pekerjaanWali\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`pendidikanWali\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`hubunganWali\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`namaWali\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`pekerjaanIbu\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`pekerjaanAyah\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`pendidikanIbu\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`pendidikanAyah\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`rtrw\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`notelp\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`kodepos\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`provinsi\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`kota\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`kelurahan\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`kecamatan\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`alamat\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`saudaraAngkat\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`saudaraTiri\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`saudaraKandung\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`bahasaSeharihari\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`tempatLahir\``);
        await queryRunner.query(`ALTER TABLE \`students\` DROP COLUMN \`namaPanggilan\``);
    }

}
