import {MigrationInterface, QueryRunner} from "typeorm";

export class updateDeposits1686733332986 implements MigrationInterface {
    name = 'updateDeposits1686733332986'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`deposits\` (\`id\` int NOT NULL AUTO_INCREMENT, \`txid\` varchar(255) NOT NULL, \`tanggalDeposit\` datetime NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`dendaActive\` \`dendaActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`gender\` \`gender\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`jumlahDenda\` \`jumlahDenda\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaPanggilan\` \`namaPanggilan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`agama\` \`agama\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`birthDate\` \`birthDate\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tempatLahir\` \`tempatLahir\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherName\` \`motherName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherNumber\` \`motherNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherName\` \`fatherName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherNumber\` \`fatherNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`joinDate\` \`joinDate\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`status\` \`status\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`bahasaSeharihari\` \`bahasaSeharihari\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`bloodType\` \`bloodType\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`uangKegiatan\` \`uangKegiatan\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keterangan\` \`keterangan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakBaru\` \`anakBaru\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`totalTunggakan\` \`totalTunggakan\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kewarganegaraan\` \`kewarganegaraan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakKe\` \`anakKe\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`saudaraKandung\` \`saudaraKandung\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`saudaraTiri\` \`saudaraTiri\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`saudaraAngkat\` \`saudaraAngkat\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`language\` \`language\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tinggalPada\` \`tinggalPada\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`jarakKeSekolah\` \`jarakKeSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`alamat\` \`alamat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kecamatan\` \`kecamatan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kelurahan\` \`kelurahan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kota\` \`kota\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`provinsi\` \`provinsi\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kodepos\` \`kodepos\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`notelp\` \`notelp\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`rtrw\` \`rtrw\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pendidikanAyah\` \`pendidikanAyah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pendidikanIbu\` \`pendidikanIbu\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pekerjaanAyah\` \`pekerjaanAyah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pekerjaanIbu\` \`pekerjaanIbu\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaWali\` \`namaWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`hubunganWali\` \`hubunganWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pendidikanWali\` \`pendidikanWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pekerjaanWali\` \`pekerjaanWali\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`asalSekolah\` \`asalSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaSekolah\` \`namaSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tglDanNmrIjzSTTB\` \`tglDanNmrIjzSTTB\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaSekolahAsal\` \`namaSekolahAsal\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`dariTingkat\` \`dariTingkat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`diterimaTgl\` \`diterimaTgl\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`noSuratKet\` \`noSuratKet\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tahunTamat\` \`tahunTamat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`noIjzahSTTB\` \`noIjzahSTTB\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`melanjutKeSekolah\` \`melanjutKeSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kelasDitinggalkan\` \`kelasDitinggalkan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keSekolah\` \`keSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keTingkat\` \`keTingkat\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`alasanKeluarSekolah\` \`alasanKeluarSekolah\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tglKeluar\` \`tglKeluar\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_b2731e10aef7f886a08c552290e\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tanggalBayar\` \`tanggalBayar\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`studentId\` \`studentId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_b2731e10aef7f886a08c552290e\` FOREIGN KEY (\`studentId\`) REFERENCES \`students\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_b2731e10aef7f886a08c552290e\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`studentId\` \`studentId\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tanggalBayar\` \`tanggalBayar\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_b2731e10aef7f886a08c552290e\` FOREIGN KEY (\`studentId\`) REFERENCES \`students\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tglKeluar\` \`tglKeluar\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`alasanKeluarSekolah\` \`alasanKeluarSekolah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keTingkat\` \`keTingkat\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keSekolah\` \`keSekolah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kelasDitinggalkan\` \`kelasDitinggalkan\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`melanjutKeSekolah\` \`melanjutKeSekolah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`noIjzahSTTB\` \`noIjzahSTTB\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tahunTamat\` \`tahunTamat\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`noSuratKet\` \`noSuratKet\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`diterimaTgl\` \`diterimaTgl\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`dariTingkat\` \`dariTingkat\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaSekolahAsal\` \`namaSekolahAsal\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tglDanNmrIjzSTTB\` \`tglDanNmrIjzSTTB\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaSekolah\` \`namaSekolah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`asalSekolah\` \`asalSekolah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pekerjaanWali\` \`pekerjaanWali\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pendidikanWali\` \`pendidikanWali\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`hubunganWali\` \`hubunganWali\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaWali\` \`namaWali\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pekerjaanIbu\` \`pekerjaanIbu\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pekerjaanAyah\` \`pekerjaanAyah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pendidikanIbu\` \`pendidikanIbu\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`pendidikanAyah\` \`pendidikanAyah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`rtrw\` \`rtrw\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`notelp\` \`notelp\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kodepos\` \`kodepos\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`provinsi\` \`provinsi\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kota\` \`kota\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kelurahan\` \`kelurahan\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kecamatan\` \`kecamatan\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`alamat\` \`alamat\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`jarakKeSekolah\` \`jarakKeSekolah\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tinggalPada\` \`tinggalPada\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`language\` \`language\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`saudaraAngkat\` \`saudaraAngkat\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`saudaraTiri\` \`saudaraTiri\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`saudaraKandung\` \`saudaraKandung\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakKe\` \`anakKe\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`kewarganegaraan\` \`kewarganegaraan\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`totalTunggakan\` \`totalTunggakan\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`anakBaru\` \`anakBaru\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`keterangan\` \`keterangan\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`uangKegiatan\` \`uangKegiatan\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`bloodType\` \`bloodType\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`bahasaSeharihari\` \`bahasaSeharihari\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`status\` \`status\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`joinDate\` \`joinDate\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherNumber\` \`fatherNumber\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`fatherName\` \`fatherName\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherNumber\` \`motherNumber\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`motherName\` \`motherName\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`tempatLahir\` \`tempatLahir\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`birthDate\` \`birthDate\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`agama\` \`agama\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`namaPanggilan\` \`namaPanggilan\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`jumlahDenda\` \`jumlahDenda\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`gender\` \`gender\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`dendaActive\` \`dendaActive\` tinyint NOT NULL`);
        await queryRunner.query(`DROP TABLE \`deposits\``);
    }

}
